[project]
name = "laspectron"
version = "0.1.0"
description = "Linear Absorption Spectrometer X Ray Spectra Reconstruction"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "MACR @ git+https://github.com/cda24/MACR.git@43bafb1734c4189c52dd5bb5fbad162deac71f24",
    "lasim @ file:///Volumes/extdrivr/nocr/lasim",
    "scikit-learn>=1.9.0",
    "scikit-optimize>=0.10.2",
    "torch>=2.13.0",
    "tqdm>=4.70.0",
    "xgboost>=3.2.0",
]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.hatch.metadata]
allow-direct-references = true

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
